Using TensorFlow backend.
2019-11-27 13:40:51.937910: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/bacli/cli.py", line 69, in main
    parse_args()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/bacli/cli.py", line 63, in parse_args
    f(*args, **kwargs)
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/model_scripts/scenarioPadding.py", line 128, in run
    trainer.train(model, trainStream, valStream, iteration=index)
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/neural/trainer.py", line 226, in train
    modelInstance = model.newInstance()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/models/model.py", line 22, in newInstance
    return self._buildModel()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/models/modelPadded.py", line 46, in _buildModel
    model.add(BatchNormalization())
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/sequential.py", line 181, in add
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/base_layer.py", line 457, in __call__
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/layers/normalization.py", line 185, in call
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 1858, in normalize_batch_in_training
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 292, in _has_nchw_support
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 278, in _get_available_gpus
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 186, in get_session
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
Using TensorFlow backend.
2019-11-27 13:41:03.958290: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/bacli/cli.py", line 69, in main
    parse_args()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/bacli/cli.py", line 63, in parse_args
    f(*args, **kwargs)
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/model_scripts/scenarioPadding.py", line 128, in run
    trainer.train(model, trainStream, valStream, iteration=index)
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/neural/trainer.py", line 226, in train
    modelInstance = model.newInstance()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/models/model.py", line 22, in newInstance
    return self._buildModel()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/models/modelPadded.py", line 46, in _buildModel
    model.add(BatchNormalization())
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/sequential.py", line 181, in add
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/base_layer.py", line 457, in __call__
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/layers/normalization.py", line 185, in call
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 1858, in normalize_batch_in_training
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 292, in _has_nchw_support
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 278, in _get_available_gpus
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 186, in get_session
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
Using TensorFlow backend.
2019-11-27 13:41:16.461967: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/bacli/cli.py", line 69, in main
    parse_args()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/bacli/cli.py", line 63, in parse_args
    f(*args, **kwargs)
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/model_scripts/scenarioPadding.py", line 128, in run
    trainer.train(model, trainStream, valStream, iteration=index)
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/neural/trainer.py", line 226, in train
    modelInstance = model.newInstance()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/models/model.py", line 22, in newInstance
    return self._buildModel()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/models/modelPadded.py", line 46, in _buildModel
    model.add(BatchNormalization())
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/sequential.py", line 181, in add
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/base_layer.py", line 457, in __call__
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/layers/normalization.py", line 185, in call
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 1858, in normalize_batch_in_training
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 292, in _has_nchw_support
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 278, in _get_available_gpus
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 186, in get_session
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
Using TensorFlow backend.
2019-11-27 13:41:32.833682: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/bacli/cli.py", line 69, in main
    parse_args()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/bacli/cli.py", line 63, in parse_args
    f(*args, **kwargs)
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/model_scripts/scenarioPadding.py", line 128, in run
    trainer.train(model, trainStream, valStream, iteration=index)
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/neural/trainer.py", line 226, in train
    modelInstance = model.newInstance()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/models/model.py", line 22, in newInstance
    return self._buildModel()
  File "/scratch/antwerpen/203/vsc20380/deepTCR-rework/src/models/modelPadded.py", line 46, in _buildModel
    model.add(BatchNormalization())
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/sequential.py", line 181, in add
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/base_layer.py", line 457, in __call__
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/layers/normalization.py", line 185, in call
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 1858, in normalize_batch_in_training
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 292, in _has_nchw_support
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 278, in _get_available_gpus
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 186, in get_session
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/apps/antwerpen/broadwell/centos7/TensorFlow/1.12.0-intel-2018b-GPU-Python-3.6.8-Keras-2.2.4/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
Using TensorFlow backend.
2019-11-27 13:41:47.303856: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-27 13:41:48.825488: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:03:00.0
totalMemory: 15.90GiB freeMemory: 15.64GiB
2019-11-27 13:41:48.825545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-11-27 13:41:49.214118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-27 13:41:49.214172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-11-27 13:41:49.214180: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-11-27 13:41:49.214285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15155 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:03:00.0, compute capability: 6.0)
Using TensorFlow backend.
2019-11-27 13:59:06.638751: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-27 13:59:07.968195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:03:00.0
totalMemory: 15.90GiB freeMemory: 15.64GiB
2019-11-27 13:59:07.968246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-11-27 13:59:08.273210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-27 13:59:08.273265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-11-27 13:59:08.273273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-11-27 13:59:08.273377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15155 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:03:00.0, compute capability: 6.0)
Using TensorFlow backend.
2019-11-27 14:14:10.370944: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-27 14:14:11.966509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:03:00.0
totalMemory: 15.90GiB freeMemory: 15.64GiB
2019-11-27 14:14:11.966570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-11-27 14:14:12.375770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-27 14:14:12.375834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-11-27 14:14:12.375858: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-11-27 14:14:12.375994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15155 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:03:00.0, compute capability: 6.0)
